Create tree.h
Anuiel/set-on-aa-tree pull request #1
Opened 2022-03-19 15:46 UTC by Anuiel

2022-03-20 20:30 UTC, Gleb-Tretyakov requested changes

2022-03-20 20:30 UTC, Gleb-Tretyakov commented on tree.h
> +        Node(const ValueType &value, Node *left, Node *right, Node *parent, size_t level = 1) :
Как по мне строчка длинная, надо переносить

2022-03-20 20:30 UTC, Gleb-Tretyakov commented on tree.h
> +        Node(const ValueType &value, Node *left, Node *right, Node *parent, size_t level = 1) :
все числа в константы

2022-03-20 20:30 UTC, Gleb-Tretyakov commented on tree.h
> +    Node *root_;
Все POD'ы https://en.wikipedia.org/wiki/Passive_data_structure
инициаизируем явно

2022-03-20 20:30 UTC, Gleb-Tretyakov commented on tree.h
> +    static Node *DeepCopy(Node *node, Node *pred = nullptr) {
а тут и возможно где-то дальше const не нужен?

2022-03-20 20:30 UTC, Gleb-Tretyakov commented on tree.h
> +        iterator &operator--() {
iterator& ну и везде, где * или & пишем около типа

2022-03-20 20:30 UTC, Gleb-Tretyakov commented on tree.h
> +    // TODO: make this O(1) if needed
TODO?

2022-03-20 20:30 UTC, Gleb-Tretyakov commented on tree.h
> +        auto cur_node = root_;
без auto

2022-03-20 20:30 UTC, Gleb-Tretyakov commented on tree.h
> +    static Node *erase(Node *root, const ValueType &value, bool &was_erased) {
Ох-ох-ох, какая страшная функция, надо исправлять

2022-03-20 21:02 UTC, Anuiel commented on tree.h
> +        Node(const ValueType &value, Node *left, Node *right, Node *parent, size_t level = 1) :
```
        Node(const ValueType& value, Node* left, Node* right, Node* parent, size_t level = 1) :
                value(value), 
                left(left), 
                right(right), 
                parent(parent), 
                level(level) 
        {}
```
Или как

2022-03-20 21:03 UTC, Anuiel commented on tree.h
> +    static Node *erase(Node *root, const ValueType &value, bool &was_erased) {
Что такое страшная функция?

2022-03-20 21:07 UTC, Anuiel commented on tree.h
> +    static Node *DeepCopy(Node *node, Node *pred = nullptr) {
static метод не может быть const (по крайней мере CLion ругается, когда ставлю)

2022-03-30 16:43 UTC, Gleb-Tretyakov commented
У тебя конфликты, порезолвь issue, пришли ссылку на посылку

2022-03-30 16:46 UTC, Gleb-Tretyakov commented on tree.h
> +    static Node* DeepCopy(Node* node, Node* pred = nullptr) {
Все кроме Node уносим под public раздел

2022-03-30 16:46 UTC, Gleb-Tretyakov commented on tree.h
> +                value(value), left(left), right(right), parent(parent), level(level) {}
А зачем у структур так делать, просто напиши в теле функции через =, читаемее будет

2022-03-30 16:46 UTC, Gleb-Tretyakov commented on tree.h
> +        size_t level;
явная инциализация тут и везде (указатели это нулл)

2022-03-30 16:46 UTC, Gleb-Tretyakov commented on tree.h
> +            auto tmp = root->left;
без auto

2022-04-05 18:28 UTC, Gleb-Tretyakov commented
Ссылку на посылку и за resolve'ь проблемы

2022-04-05 18:29 UTC, Gleb-Tretyakov commented
Сделай так, чтобы у тебя в mastser'e файлов не было. 
Иначе получается, что в file changed у тебя изменения, а не вест код новый

2022-04-13 12:09 UTC, merged